import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Core Palette & Tonal Surfaces (InRumo Institutional)
        primary: {
          DEFAULT: '#7e5700',
          foreground: '#ffffff',
          container: '#c9932e',
          'on-container': '#483000',
          fixed: '#ffdeac',
          'fixed-dim': '#f8bc54',
          'on-fixed': '#281900',
          'on-fixed-variant': '#604100',
          inverse: '#f8bc54',
        },
        secondary: {
          DEFAULT: '#5f5e5e',
          foreground: '#ffffff',
          container: '#e2dfde',
          'on-container': '#636262',
          fixed: '#e5e2e1',
          'fixed-dim': '#c8c6c5',
          'on-fixed': '#1c1b1b',
          'on-fixed-variant': '#474746',
        },
        tertiary: {
          DEFAULT: '#1c619d',
          foreground: '#ffffff',
          container: '#66a0e0',
          'on-container': '#00365e',
          fixed: '#d1e4ff',
          'fixed-dim': '#9ecaff',
          'on-fixed': '#001d36',
          'on-fixed-variant': '#00497d',
        },
        surface: {
          DEFAULT: '#fbf8ff',
          dim: '#dad9e3',
          bright: '#fbf8ff',
          variant: '#e3e1ec',
          tint: '#7e5700',
          'on-surface': '#1a1b22',
          'on-variant': '#504536',
          'container-lowest': '#ffffff',
          'container-low': '#f4f2fd',
          container: '#eeedf7',
          'container-high': '#e8e7f1',
          'container-highest': '#e3e1ec',
          inverse: '#2f3038',
          'on-inverse': '#f1effa',
        },
        background: {
          DEFAULT: '#fbf8ff',
          'on-background': '#1a1b22',
        },
        outline: {
          DEFAULT: '#827564',
          variant: '#d4c4b0',
        },
        error: {
          DEFAULT: '#ba1a1a',
          foreground: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
      },
      fontFamily: {
        heading: ['Space Grotesk', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'container-max': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
    },
  },
  plugins: [],
} satisfies Config;